name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    #   name: Checkout
    #   uses: actions/checkout@v2
    # - name: Setup Node
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: 'lts/*'
    # - name: Install dependencies
    #   run: npm ci
    # - name: Release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   run: npx semantic-release
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
